name: Build Windows MSI

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create release'
        required: false
        default: false
        type: boolean
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: false
        default: ''
        type: string
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows-msi:
    runs-on: windows-latest
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          
      - name: Install WiX Toolset
        run: |
          # Try chocolatey first (most reliable)
          try {
            Write-Host "Installing WiX via Chocolatey..."
            choco install wixtoolset -y --version=3.11.2
            $wixDir = "${env:ProgramFiles(x86)}\WiX Toolset v3.11\bin"
            if (Test-Path $wixDir) {
              echo "$wixDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              echo "WIX=$wixDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
              Write-Host "WiX installed via Chocolatey successfully"
              exit 0
            }
          } catch {
            Write-Host "Chocolatey installation failed, trying manual download..."
          }
          
          # Fallback to manual download with retry logic
          $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip"
          $wixZip = "$env:TEMP\wix311-binaries.zip"
          $wixDir = "C:\wix311"
          $maxRetries = 3
          $retryCount = 0
          
          do {
            try {
              $retryCount++
              Write-Host "Downloading WiX Toolset (attempt $retryCount/$maxRetries)..."
              
              # Remove existing files if they exist
              if (Test-Path $wixZip) { Remove-Item $wixZip -Force }
              if (Test-Path $wixDir) { Remove-Item $wixDir -Recurse -Force }
              
              # Download with progress and timeout
              $webClient = New-Object System.Net.WebClient
              $webClient.DownloadFile($wixUrl, $wixZip)
              
              # Verify download
              if (-not (Test-Path $wixZip) -or (Get-Item $wixZip).Length -eq 0) {
                throw "Download failed or file is empty"
              }
              
              Write-Host "Extracting WiX Toolset..."
              New-Item -ItemType Directory -Path $wixDir -Force
              Expand-Archive -Path $wixZip -DestinationPath $wixDir -Force
              
              # Verify extraction
              if (-not (Test-Path "$wixDir\candle.exe") -or -not (Test-Path "$wixDir\light.exe")) {
                throw "WiX extraction failed - required executables not found"
              }
              
              Write-Host "WiX Toolset downloaded and extracted successfully"
              break
            } catch {
              Write-Host "Attempt $retryCount failed: $($_.Exception.Message)"
              if ($retryCount -ge $maxRetries) {
                Write-Error "Failed to download WiX Toolset after $maxRetries attempts"
                exit 1
              }
              Start-Sleep -Seconds 5
            }
          } while ($retryCount -lt $maxRetries)
          
          Write-Host "Adding WiX to PATH..."
          echo "$wixDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
          Write-Host "Setting WiX environment variables..."
          echo "WIX=$wixDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "WIX_TOOLSET_PATH=$wixDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
          Write-Host "Verifying WiX installation..."
          if (Test-Path "$wixDir\candle.exe" -and Test-Path "$wixDir\light.exe") {
            & "$wixDir\candle.exe" -? | Select-Object -First 3
            & "$wixDir\light.exe" -? | Select-Object -First 3
            Write-Host "WiX installation verified successfully"
            
            # List all files in WiX directory for debugging
            Write-Host "WiX directory contents:"
            Get-ChildItem $wixDir | ForEach-Object { Write-Host "  $($_.Name)" }
          } else {
            Write-Error "WiX installation failed - required executables not found"
            if (Test-Path $wixDir) {
              Write-Host "Directory contents:"
              Get-ChildItem $wixDir -Recurse | ForEach-Object { Write-Host "  $($_.FullName)" }
            }
            exit 1
          }
          
      - name: Determine version
        id: version
        run: |
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            $version = "v0.1.0-dev"
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version: $version"
          
      - name: Install frontend dependencies
        run: npm ci
        
      - name: Build frontend
        run: npm run build:prod
        
      - name: Verify WiX Environment Before Build
        run: |
          Write-Host "Verifying WiX environment before build..."
          Write-Host "WIX: $env:WIX"
          Write-Host "WIX_TOOLSET_PATH: $env:WIX_TOOLSET_PATH"
          Write-Host "PATH contains WiX: $($env:PATH -like '*wix311*')"
          
          # Verify WiX executables are accessible
          $wixDir = "C:\wix311"
          if (Test-Path "$wixDir\candle.exe") {
            Write-Host "✓ candle.exe found and accessible"
            & "$wixDir\candle.exe" -? 2>&1 | Select-Object -First 2
          } else {
            Write-Error "✗ candle.exe not found at $wixDir\candle.exe"
            exit 1
          }
          
          if (Test-Path "$wixDir\light.exe") {
            Write-Host "✓ light.exe found and accessible"
            & "$wixDir\light.exe" -? 2>&1 | Select-Object -First 2
          } else {
            Write-Error "✗ light.exe not found at $wixDir\light.exe"
            exit 1
          }
          
          Write-Host "WiX environment verification completed successfully"
          
      - name: Build Tauri MSI
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIX: C:\wix311
          WIX_TOOLSET_PATH: C:\wix311
          PATH: C:\wix311;${{ env.PATH }}
          # Additional environment variables for WiX
          WIXUI_INSTALLDIR: C:\wix311
          WIX_TEMP: ${{ runner.temp }}\wix
        with:
          tagName: ${{ steps.version.outputs.version }}
          releaseName: "Clipify ${{ steps.version.outputs.version }}"
          releaseBody: |
            ## Windows MSI Installer
            
            This release includes a Windows MSI installer for Clipify.
            
            ### Installation
            1. Download the `.msi` file from the assets below
            2. Run the installer as administrator
            3. Follow the installation wizard
            
            ### Features
            - Global hotkey support (Cmd+Shift+C)
            - AI-powered text cleanup and rephrasing
            - Secure authentication with JWT tokens
            - System tray integration
            
            ### System Requirements
            - Windows 10 or later
            - Microsoft Edge WebView2 (automatically installed if missing)
          releaseDraft: ${{ github.event.inputs.release != 'true' }}
          prerelease: ${{ contains(steps.version.outputs.version, 'dev') || contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta') }}
          includeDebug: false
          includeRelease: true
          args: --bundles msi --config src-tauri/tauri.conf.json --verbose
          
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: clipify-windows-msi-${{ steps.version.outputs.version }}
          path: src-tauri/target/release/bundle/msi/*.msi
          retention-days: 30
          
      - name: List build artifacts
        run: |
          echo "Build completed successfully!"
          echo "MSI files:"
          Get-ChildItem -Path "src-tauri/target/release/bundle/msi/" -Filter "*.msi" | ForEach-Object { 
            echo "  - $($_.Name) ($([math]::Round($_.Length / 1MB, 2)) MB)"
          }
