name: Build Windows MSI

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create release'
        required: false
        default: false
        type: boolean
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: false
        default: ''
        type: string
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows-msi:
    runs-on: windows-latest
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          
      - name: Install WiX Toolset
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix311-binaries.zip"
          Expand-Archive -Path "wix311-binaries.zip" -DestinationPath "C:\wix"
          echo "C:\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Determine version
        id: version
        run: |
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            $version = "v0.1.0-dev"
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version: $version"
          
      - name: Install frontend dependencies
        run: npm ci
        
      - name: Build frontend
        run: npm run build:prod
        
      - name: Build Tauri MSI
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.version.outputs.version }}
          releaseName: "Clipify ${{ steps.version.outputs.version }}"
          releaseBody: |
            ## Windows MSI Installer
            
            This release includes a Windows MSI installer for Clipify.
            
            ### Installation
            1. Download the `.msi` file from the assets below
            2. Run the installer as administrator
            3. Follow the installation wizard
            
            ### Features
            - Global hotkey support (Cmd+Shift+C)
            - AI-powered text cleanup and rephrasing
            - Secure authentication with JWT tokens
            - System tray integration
            
            ### System Requirements
            - Windows 10 or later
            - Microsoft Edge WebView2 (automatically installed if missing)
          releaseDraft: ${{ github.event.inputs.release != 'true' }}
          prerelease: ${{ contains(steps.version.outputs.version, 'dev') || contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta') }}
          includeDebug: false
          includeRelease: true
          
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: clipify-windows-msi-${{ steps.version.outputs.version }}
          path: src-tauri/target/release/bundle/msi/*.msi
          retention-days: 30
          
      - name: List build artifacts
        run: |
          echo "Build completed successfully!"
          echo "MSI files:"
          Get-ChildItem -Path "src-tauri/target/release/bundle/msi/" -Filter "*.msi" | ForEach-Object { 
            echo "  - $($_.Name) ($([math]::Round($_.Length / 1MB, 2)) MB)"
          }
