name: Build Windows MSI

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Create release"
        required: false
        default: false
        type: boolean
      version:
        description: "Version tag (e.g., v1.0.0)"
        required: false
        default: ""
        type: string
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main, master]

jobs:
  build-windows-msi:
    runs-on: windows-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install WiX Toolset
        run: |
          Write-Host "Installing WiX Toolset v3.14.1..."

          # Use chocolatey for reliable WiX installation
          Write-Host "Installing WiX via Chocolatey..."
          choco install wixtoolset --version=3.14.1 --force --no-progress

          # Refresh environment variables using PowerShell method
          Write-Host "Refreshing environment variables..."
          try {
            Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
            refreshenv
            Write-Host "✅ Environment variables refreshed"
          } catch {
            Write-Host "⚠️ Could not refresh environment via Chocolatey profile: $_"
            Write-Host "Continuing with manual PATH setup..."
          }

          # Verify installation
          Write-Host "Verifying WiX installation..."
          $wixPath = "${env:ProgramFiles(x86)}\WiX Toolset v3.14\bin"

          if (Test-Path "$wixPath\candle.exe") {
            Write-Host "✅ WiX found at: $wixPath"
            
            # Add to PATH and set environment variables for GitHub Actions
            echo "$wixPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            echo "WIX=$wixPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            
            # Also update current session PATH
            $env:PATH = "$wixPath;$env:PATH"
            
            # Test functionality
            try {
              $candleVersion = & "$wixPath\candle.exe" -? 2>&1 | Select-Object -First 1
              Write-Host "✅ Candle version: $candleVersion"
            } catch {
              Write-Warning "WiX tools may have issues: $_"
            }
          } else {
            Write-Error "❌ WiX installation failed - tools not found at expected location"
            
            # Try to find WiX in other common locations
            $alternatePaths = @(
              "${env:ProgramFiles}\WiX Toolset v3.14\bin",
              "C:\Program Files (x86)\WiX Toolset v3.14\bin",
              "C:\Program Files\WiX Toolset v3.14\bin"
            )
            
            foreach ($altPath in $alternatePaths) {
              if (Test-Path "$altPath\candle.exe") {
                Write-Host "✅ Found WiX at alternate location: $altPath"
                echo "$altPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
                echo "WIX=$altPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
                $env:PATH = "$altPath;$env:PATH"
                exit 0
              }
            }
            
            Write-Error "❌ WiX installation failed - could not locate tools"
            exit 1
          }

      - name: Determine version
        id: version
        run: |
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            $version = "v0.1.0-dev"
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version: $version"

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build:prod

      - name: Build Tauri MSI
        run: |
          Write-Host "Starting Tauri MSI build..."

          # Verify WiX is accessible
          Write-Host "Current WiX environment:"
          Write-Host "  WIX: $env:WIX"
          Write-Host "  PATH contains WiX: $($env:PATH -like '*WiX*')"

          # Verify WiX tools are accessible
          try {
            $candleTest = & "candle.exe" -? 2>&1 | Select-Object -First 1
            Write-Host "✅ WiX candle.exe accessible: $candleTest"
          } catch {
            Write-Host "❌ Cannot access candle.exe: $_"
            
            # Try to find WiX manually
            $possiblePaths = @(
              "${env:ProgramFiles(x86)}\WiX Toolset v3.14\bin",
              "${env:ProgramFiles}\WiX Toolset v3.14\bin",
              "C:\Program Files (x86)\WiX Toolset v3.14\bin"
            )
            
            foreach ($path in $possiblePaths) {
              if (Test-Path "$path\candle.exe") {
                Write-Host "Found WiX at: $path"
                $env:PATH = "$path;$env:PATH"
                break
              }
            }
          }

          # Final verification
          try {
            & "candle.exe" -? | Select-Object -First 1
            Write-Host "✅ WiX tools ready for Tauri build"
          } catch {
            Write-Error "❌ WiX tools still not accessible. Build will likely fail."
            exit 1
          }

          # Verify Tauri config exists
          if (-not (Test-Path "src-tauri/tauri.conf.json")) {
            Write-Error "❌ Tauri configuration file not found"
            exit 1
          }

          # Build MSI package with Tauri CLI
          Write-Host "Building MSI package..."
          try {
            npm run tauri:build -- --bundles msi --verbose
            Write-Host "✅ MSI build completed successfully"
          } catch {
            Write-Error "❌ Tauri build failed: $_"
            exit 1
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: ${{ github.event.inputs.release == 'true' || github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: "Clipify ${{ steps.version.outputs.version }}"
          body: |
            ## Windows MSI Installer

            This release includes a Windows MSI installer for Clipify.

            ### Installation
            1. Download the `.msi` file from the assets below
            2. Run the installer as administrator
            3. Follow the installation wizard

            ### Features
            - Global hotkey support (Cmd+Shift+C)
            - AI-powered text cleanup and rephrasing
            - Secure authentication with JWT tokens
            - System tray integration

            ### System Requirements
            - Windows 10 or later
            - Microsoft Edge WebView2 (automatically installed if missing)
          draft: ${{ github.event.inputs.release != 'true' }}
          prerelease: ${{ contains(steps.version.outputs.version, 'dev') || contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta') }}
          files: |
            src-tauri/target/release/bundle/msi/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: clipify-windows-msi-${{ steps.version.outputs.version }}
          path: src-tauri/target/release/bundle/msi/*.msi
          retention-days: 30

      - name: Verify and list build artifacts
        run: |
          Write-Host "=== Build Verification ==="
          
          $msiPath = "src-tauri/target/release/bundle/msi"
          
          if (Test-Path $msiPath) {
            $msiFiles = Get-ChildItem -Path $msiPath -Filter "*.msi"
            
            if ($msiFiles.Count -gt 0) {
              Write-Host "✅ Build completed successfully!"
              Write-Host "MSI files generated:"
              $msiFiles | ForEach-Object { 
                $sizeMB = [math]::Round($_.Length / 1MB, 2)
                Write-Host "  - $($_.Name) ($sizeMB MB)"
                Write-Host "    Full path: $($_.FullName)"
              }
            } else {
              Write-Error "❌ No MSI files found in output directory"
              exit 1
            }
          } else {
            Write-Error "❌ MSI output directory not found: $msiPath"
            Write-Host "Available directories in target/release/bundle:"
            if (Test-Path "src-tauri/target/release/bundle") {
              Get-ChildItem "src-tauri/target/release/bundle" | Format-Table Name, ItemType
            }
            exit 1
          }
