name: Build Windows MSI

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create release'
        required: false
        default: false
        type: boolean
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: false
        default: ''
        type: string
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows-msi:
    runs-on: windows-latest
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          
      - name: Install WiX Toolset
        run: |
          # Try chocolatey first (most reliable)
          try {
            Write-Host "Installing WiX via Chocolatey..."
            choco install wixtoolset -y --version=3.11.2
            $wixDir = "${env:ProgramFiles(x86)}\WiX Toolset v3.11\bin"
            if (Test-Path $wixDir) {
              echo "$wixDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              echo "WIX=$wixDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
              Write-Host "WiX installed via Chocolatey successfully"
              exit 0
            }
          } catch {
            Write-Host "Chocolatey installation failed, trying manual download..."
          }
          
          # Fallback to manual download
          $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip"
          $wixZip = "$env:TEMP\wix311-binaries.zip"
          $wixDir = "C:\wix311"
          
          Write-Host "Downloading WiX Toolset..."
          Invoke-WebRequest -Uri $wixUrl -OutFile $wixZip -UseBasicParsing
          
          Write-Host "Extracting WiX Toolset..."
          New-Item -ItemType Directory -Path $wixDir -Force
          Expand-Archive -Path $wixZip -DestinationPath $wixDir -Force
          
          Write-Host "Adding WiX to PATH..."
          echo "$wixDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
          Write-Host "Setting WiX environment variables..."
          echo "WIX=$wixDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "WIX_TOOLSET_PATH=$wixDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
          Write-Host "Verifying WiX installation..."
          if (Test-Path "$wixDir\candle.exe") {
            & "$wixDir\candle.exe" -? | Select-Object -First 3
            & "$wixDir\light.exe" -? | Select-Object -First 3
            Write-Host "WiX installation verified successfully"
          } else {
            Write-Error "WiX installation failed - candle.exe not found"
            exit 1
          }
          
      - name: Determine version
        id: version
        run: |
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            $version = "v0.1.0-dev"
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version: $version"
          
      - name: Install frontend dependencies
        run: npm ci
        
      - name: Build frontend
        run: npm run build:prod
        
      - name: Build Tauri MSI
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIX: C:\wix311
          WIX_TOOLSET_PATH: C:\wix311
          PATH: C:\wix311;${{ env.PATH }}
        with:
          tagName: ${{ steps.version.outputs.version }}
          releaseName: "Clipify ${{ steps.version.outputs.version }}"
          releaseBody: |
            ## Windows MSI Installer
            
            This release includes a Windows MSI installer for Clipify.
            
            ### Installation
            1. Download the `.msi` file from the assets below
            2. Run the installer as administrator
            3. Follow the installation wizard
            
            ### Features
            - Global hotkey support (Cmd+Shift+C)
            - AI-powered text cleanup and rephrasing
            - Secure authentication with JWT tokens
            - System tray integration
            
            ### System Requirements
            - Windows 10 or later
            - Microsoft Edge WebView2 (automatically installed if missing)
          releaseDraft: ${{ github.event.inputs.release != 'true' }}
          prerelease: ${{ contains(steps.version.outputs.version, 'dev') || contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta') }}
          includeDebug: false
          includeRelease: true
          args: --bundles msi
          
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: clipify-windows-msi-${{ steps.version.outputs.version }}
          path: src-tauri/target/release/bundle/msi/*.msi
          retention-days: 30
          
      - name: List build artifacts
        run: |
          echo "Build completed successfully!"
          echo "MSI files:"
          Get-ChildItem -Path "src-tauri/target/release/bundle/msi/" -Filter "*.msi" | ForEach-Object { 
            echo "  - $($_.Name) ($([math]::Round($_.Length / 1MB, 2)) MB)"
          }
