name: Release

on:
  push:
    tags:
      - "v*" # Runs when you push a tag like v1.0.0

jobs:
  release:
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend deps
        run: npm install # or yarn/pnpm

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload release artifacts
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Release ${{ github.ref_name }}"
          releaseBody: "See assets below"
          draft: false
          prerelease: false